cmd_egress() {
  local mode="${1:-}" rows TAB
  running || die "no running sandbox. Start it ('sluice'), exercise it, then run 'sluice egress'."
  rows="$(egress_rows 2>/dev/null || true)"
  TAB="$(printf '\t')"
  if [ "$mode" = --json ]; then
    # Back-compat host arrays + a detailed hosts array (class/requests/bytes) for the control plane.
    local allowed blocked hosts_json="" first=1 cls host cnt byt
    allowed="$(printf '%s\n' "$rows" | awk -F"$TAB" '$1=="reached"{print $2}')"
    blocked="$(printf '%s\n' "$rows" | awk -F"$TAB" '$1=="blocked"{print $2}')"
    while IFS="$TAB" read -r cls host cnt byt; do
      [ -n "$host" ] || continue
      [ "$first" = 1 ] && first=0 || hosts_json="$hosts_json,"
      hosts_json="$hosts_json{\"host\":\"$(_json_esc "$host")\",\"class\":\"$cls\",\"requests\":$cnt,\"bytes\":$byt}"
    done <<EOF
$rows
EOF
    printf '{"box":"%s","allowed":%s,"blocked":%s,"hosts":[%s]}\n' "$(_json_esc "$container")" \
      "$(printf '%s\n' "$allowed" | _json_arr)" "$(printf '%s\n' "$blocked" | _json_arr)" "$hosts_json"
    return 0
  fi
  echo "${C_BLD}$container egress${C_RST}"
  [ -n "$rows" ] || { echo "  ${C_DIM}(nothing yet - exercise the app, then re-run)${C_RST}"; return 0; }
  # host | verdict | requests | bytes (reached): reached first (by bytes desc), then blocked.
  printf '%s\n' "$rows" | sort -t"$TAB" -k1,1r -k4,4nr -k2,2 \
    | awk -F"$TAB" -v grn="$C_GRN" -v red="$C_RED" -v rst="$C_RST" '
        function human(b){ if(b<1024) return b" B"; else if(b<1048576) return sprintf("%.1f KB",b/1024); else return sprintf("%.1f MB",b/1048576) }
        { c[NR]=$1; h[NR]=$2; n[NR]=$3; b[NR]=$4; if(length($2)>w) w=length($2) }
        END { for(i=1;i<=NR;i++){
                if(c[i]=="reached") printf "  %-*s  %s[reached]%s  %3d req   %s\n", w, h[i], grn, rst, n[i], human(b[i]);
                else                printf "  %-*s  %s[blocked]%s  %3d req\n",        w, h[i], red, rst, n[i];
              } }'
}

# sluice.lock: a committable inventory of the built image. base ref + every apk
# (name/version/checksum) + global npm pkg, introspected from the image (awk/jq run in-image via a
# heredoc), sorted for stable diffs. Defined above cmd_doctor for the early `doctor` dispatch.
current_inventory() {
  local baseref bdig
  baseref="${SLUICE_BASE_IMAGE:-cgr.dev/chainguard/wolfi-base}"
  bdig="$("$ENGINE" image inspect "$baseref" --format '{{ if .RepoDigests }}{{ index .RepoDigests 0 }}{{ end }}' 2>/dev/null || true)"
  printf 'base  %s\n' "${bdig:-$baseref}"
  "$ENGINE" run --rm -i --entrypoint sh "$tag" 2>/dev/null <<'INTROSPECT' | sort -u
awk 'BEGIN{RS="";FS="\n"}{p=v=c="";for(i=1;i<=NF;i++){t=substr($i,1,2);if(t=="P:")p=substr($i,3);else if(t=="V:")v=substr($i,3);else if(t=="C:")c=substr($i,3)}if(p!="")printf "apk  %s %s %s\n",p,v,c}' /lib/apk/db/installed
npm ls -g --depth=0 --json 2>/dev/null | jq -r '(.dependencies // {})|to_entries[]|"npm  \(.key) \(.value.version)"' 2>/dev/null
command -v pip3 >/dev/null 2>&1 && pip3 list --format=json 2>/dev/null | jq -r '.[]|"pip  \(.key//.name|ascii_downcase) \(.value//.version)"' 2>/dev/null
command -v gem  >/dev/null 2>&1 && gem list --local --quiet 2>/dev/null | awk '{name=$1;rest=$0;sub(/^[^(]*\(/,"",rest);sub(/\).*$/,"",rest);n=split(rest,vs,/, */);for(i=1;i<=n;i++){v=vs[i];sub(/^default: */,"",v);if(v!="")printf "gem  %s %s\n",name,v}}'
command -v go   >/dev/null 2>&1 && { gb=""; for d in "$(go env GOBIN 2>/dev/null)" "$(go env GOPATH 2>/dev/null)/bin" /home/sluice/go/bin; do [ -n "$d" ] && [ -d "$d" ] || continue; case " $gb " in *" $d "*) ;; *) gb="$gb $d";; esac; done; for d in $gb; do for f in "$d"/*; do [ -f "$f" ] && [ -x "$f" ] || continue; go version -m "$f" 2>/dev/null | awk '$1=="mod"{print "go  "$2" "$3; exit}'; done; done; }
command -v cargo >/dev/null 2>&1 && { for ch in "${CARGO_HOME:-$HOME/.cargo}" /home/sluice/.cargo /root/.cargo; do [ -f "$ch/.crates2.json" ] || continue; jq -r '.installs|keys[]|split(" ")|"cargo  \(.[0]) \(.[1])"' "$ch/.crates2.json" 2>/dev/null; break; done; }
true
INTROSPECT
}

# Build (if needed) and write ./sluice.lock from the image inventory.
write_lock() {
  maybe_build
  local lock="$PROJECT_DIR/sluice.lock" inv na nn np ng ngo nc parts deltarows="" had_lock=0
  inv="$(current_inventory)"
  # Capture the supply-chain delta vs the existing lock BEFORE overwriting (reuse $inv; no re-introspect).
  [ -f "$lock" ] && { had_lock=1; deltarows="$(classify_drift "$(lock_drift "$inv")")"; }
  {
    printf "# sluice.lock - inventory of the built sandbox image (%s).\n" "$tag"
    printf "# Audit/drift artifact, NOT a reproducibility guarantee (Wolfi apk is a rolling repo).\n"
    printf "# Generated by 'sluice lock'; refresh with 'sluice update'.\n"
    printf '%s\n' "$inv"
  } > "$lock"
  na="$(printf '%s\n' "$inv" | grep -c '^apk ' || true)"   # grep -c exits 1 on zero matches; tolerate
  nn="$(printf '%s\n' "$inv" | grep -c '^npm ' || true)"   # (a box with no global npm packages)
  np="$(printf '%s\n' "$inv" | grep -c '^pip ' || true)"
  ng="$(printf '%s\n' "$inv" | grep -c '^gem ' || true)"
  ngo="$(printf '%s\n' "$inv" | grep -c '^go ' || true)"
  nc="$(printf '%s\n' "$inv" | grep -c '^cargo ' || true)"
  parts="$na apk"
  [ "$nn" -gt 0 ]  && parts="$parts + $nn npm"
  [ "$np" -gt 0 ]  && parts="$parts + $np pip"
  [ "$ng" -gt 0 ]  && parts="$parts + $ng gem"
  [ "$ngo" -gt 0 ] && parts="$parts + $ngo go"
  [ "$nc" -gt 0 ]  && parts="$parts + $nc cargo"
  echo "[sluice] wrote $lock ($parts packages)"
  if [ "$had_lock" = 1 ] && [ -n "$deltarows" ]; then
    echo "[sluice] supply-chain delta since last lock: +$(printf '%s\n' "$deltarows" | grep -c '^add' || true) -$(printf '%s\n' "$deltarows" | grep -c '^del' || true) ~$(printf '%s\n' "$deltarows" | grep -c '^chg' || true)"
    printf '%s\n' "$deltarows" | render_drift_human
  fi
}

# Drifted lines between ./sluice.lock and the live image inventory ("< lock / > current"); empty =
# in sync. Optional $1 = a pre-computed inventory (so doctor doesn't introspect the image twice).
lock_drift() {
  local inv="${1:-$(current_inventory 2>/dev/null || true)}"
  diff <(grep -vE '^#' "$PROJECT_DIR/sluice.lock" 2>/dev/null || true) \
       <(printf '%s\n' "$inv") 2>/dev/null | grep -E '^[<>]' || true
}

# Classify raw lock_drift ("< old" / "> new") into sorted structured rows:
# "<op>\t<type>\t<name>\t<old>\t<new>", op = add|del|chg. $1 = pre-computed raw drift (else read fresh).
classify_drift() {
  local raw TAB; TAB="$(printf '\t')"
  if [ $# -ge 1 ]; then raw="$1"; else raw="$(lock_drift)"; fi
  [ -n "$raw" ] || return 0
  printf '%s\n' "$raw" | awk '
    { type=$2;
      if (type=="base") { key="base"; name="base"; val=$3 }
      else              { key=type SUBSEP $3; name=$3; val=$4 }
      if ($1=="<") oldv[key]=val; else newv[key]=val;
      t[key]=type; nm[key]=name; seen[key]=1 }
    END{ for (k in seen) { o=oldv[k]; n=newv[k];
      if (o!="" && n=="")      printf "del\t%s\t%s\t%s\t\n",  t[k],nm[k],o;
      else if (o=="" && n!="") printf "add\t%s\t%s\t\t%s\n",  t[k],nm[k],n;
      else                     printf "chg\t%s\t%s\t%s\t%s\n",t[k],nm[k],o,n } }' \
  | sort -t"$TAB" -k2,2 -k3,3
}

# Render structured drift rows (stdin) as aligned, colored +/-/~ lines. $1=err -> stderr-gated colors
# (the --check path renders to stderr; write_lock/--diff render to stdout).
render_drift_human() {
  local g="$C_GRN" r="$C_RED" y="$C_YEL" x="$C_RST"
  [ "${1:-}" = err ] && { g="$E_GRN"; r="$E_RED"; y="$E_YEL"; x="$E_RST"; }
  awk -F"$(printf '\t')" -v g="$g" -v r="$r" -v y="$y" -v x="$x" '
    { op[NR]=$1; ty[NR]=$2; nm[NR]=$3; ov[NR]=$4; nv[NR]=$5;
      if(length($2)>wt)wt=length($2); if(length($3)>wn)wn=length($3) }
    END{ for(i=1;i<=NR;i++){
      sym=(op[i]=="add")?"+":(op[i]=="del")?"-":"~";
      col=(op[i]=="add")?g:(op[i]=="del")?r:y;
      if(op[i]=="chg")      printf "  %s%s%s %-*s %-*s %s  ->  %s\n", col,sym,x, wt,ty[i], wn,nm[i], ov[i], nv[i];
      else if(op[i]=="add") printf "  %s%s%s %-*s %-*s %s\n",          col,sym,x, wt,ty[i], wn,nm[i], nv[i];
      else                  printf "  %s%s%s %-*s %-*s %s\n",          col,sym,x, wt,ty[i], wn,nm[i], ov[i] } }'
}

# Render structured drift rows (stdin) as {in_sync,added,removed,changed[]} for CI.
render_drift_json() {
  awk -F"$(printf '\t')" '
    function j(s){ gsub(/\\/,"\\\\",s); gsub(/"/,"\\\"",s); return s }
    { if($1=="add")      a=a (a==""?"":",") sprintf("{\"type\":\"%s\",\"name\":\"%s\",\"version\":\"%s\"}",j($2),j($3),j($5));
      else if($1=="del") d=d (d==""?"":",") sprintf("{\"type\":\"%s\",\"name\":\"%s\",\"version\":\"%s\"}",j($2),j($3),j($4));
      else               c=c (c==""?"":",") sprintf("{\"type\":\"%s\",\"name\":\"%s\",\"from\":\"%s\",\"to\":\"%s\"}",j($2),j($3),j($4),j($5));
      n++ }
    END{ printf "{\"in_sync\":%s,\"added\":[%s],\"removed\":[%s],\"changed\":[%s]}\n", (n==0?"true":"false"), a, d, c }'
}

# Shared drift report for --check (exit 1 on drift), --diff (exit 0), and --enforce (strict). $1 =
# exit-on-drift, $2 = --json|"", $3 = strict|"" (refuse to build/tolerate a stale image - a pure verifier).
_drift_report() {
  local on_drift="$1" json=0 strict=0; [ "${2:-}" = --json ] && json=1; [ "${3:-}" = strict ] && strict=1
  [ -f "$PROJECT_DIR/sluice.lock" ] || die "no sluice.lock to check against - run 'sluice lock' first"
  # A check verifies the artifact as built: build only if no image exists; if the image predates a
  # config edit, note it (on stderr, so --json stays clean) but still report against what's built -
  # a gate shouldn't silently rebuild (that's `sluice build`/`sluice lock`). --enforce is stricter
  # still: it refuses to build or to report against a stale image (a CI gate must not mutate).
  if image_missing; then [ "$strict" = 1 ] && die "no built image to enforce against - run 'sluice build' first"; build
  elif image_stale; then [ "$strict" = 1 ] && die "image predates config edits - rebuild before 'sluice lock --enforce'"; echo "[sluice] ${E_YEL}note${E_RST}: image predates config edits - run 'sluice build' to refresh" >&2; fi
  local rows; rows="$(classify_drift)"
  if [ "$json" = 1 ]; then
    [ -z "$rows" ] && { echo '{"in_sync":true,"added":[],"removed":[],"changed":[]}'; return 0; }
    printf '%s\n' "$rows" | render_drift_json; return "$on_drift"
  fi
  [ -z "$rows" ] && { echo "[sluice] ${C_GRN}lock in sync${C_RST}"; return 0; }
  if [ "$on_drift" = 1 ]; then
    echo "[sluice] ${E_RED}DRIFT${E_RST}: the built image differs from sluice.lock (+added -removed ~changed):" >&2
    printf '%s\n' "$rows" | render_drift_human err >&2
  else
    echo "[sluice] drift from sluice.lock (+added -removed ~changed):"
    printf '%s\n' "$rows" | render_drift_human
  fi
  return "$on_drift"
}

# `sluice lock --check [--json]`: fail (exit 1) if the built image drifted from the committed sluice.lock.
cmd_lock_check() { _drift_report 1 "${1:-}"; }
# `sluice lock --diff [--json]`: same drift view, read-only (exit 0) - a local review, not a CI gate.
cmd_lock_diff()  { _drift_report 0 "${1:-}"; }
# `sluice lock --enforce [--json]`: a strict CI gate - like --check, but refuses to build or to tolerate
# a stale image (verify the committed lock against the image as-built, no side effects). Gates against
# the committed lock, not bit-reproducibility (Wolfi apk is a rolling repo).
cmd_lock_enforce() { _drift_report 1 "${1:-}" strict; }

# `sluice lock --sbom [--format cyclonedx|spdx]`: a deterministic SBOM (apk + npm + pip + gem + go +
# cargo purls) to stdout. Assembled in-image (jq lives there); apk components carry their SHA-1 integrity
# hash (the db's Q1 checksum, hex-decoded). No timestamp/serial + purl-sorted so it's byte-stable;
# base/toolver/tag via env. Default CycloneDX 1.6; --format spdx emits the same package set as SPDX 2.3.
cmd_sbom() {
  local fmt=cyclonedx
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --format)   fmt="${2:-}"; [ -n "$fmt" ] || die "usage: sluice lock --sbom [--format cyclonedx|spdx]"; shift ;;
      --format=*) fmt="${1#--format=}" ;;
      *)          die "usage: sluice lock --sbom [--format cyclonedx|spdx]" ;;
    esac
    shift
  done
  case "$fmt" in cyclonedx|spdx) ;; *) die "invalid --sbom format '$fmt' (cyclonedx|spdx)" ;; esac
  maybe_build; _sbom_for "$tag" "$fmt"
}

# Emit the CycloneDX SBOM for an arbitrary image ref (introspected in-image). cmd_sbom passes the built
# project $tag; the hidden __sbom arm passes the base ref (so CI can attest the base's own SBOM).
_sbom_for() {
  local img="$1" baseref bdig
  baseref="${SLUICE_BASE_IMAGE:-cgr.dev/chainguard/wolfi-base}"
  bdig="$("$ENGINE" image inspect "$baseref" --format '{{ if .RepoDigests }}{{ index .RepoDigests 0 }}{{ end }}' 2>/dev/null || true)"
  "$ENGINE" run --rm -i -e "SBOM_BASE=${bdig:-$baseref}" -e "SBOM_TOOLVER=$SLUICE_VERSION" -e "SBOM_IMAGE=$img" \
    -e "SBOM_FORMAT=${2:-cyclonedx}" --entrypoint sh "$img" 2>/dev/null <<'SBOM'
SBOM_ARCH="$(apk --print-arch 2>/dev/null || uname -m)"; export SBOM_ARCH
{
  # apk: name, version, and the Q1<base64-sha1> checksum decoded to hex (4th field; empty if undecodable).
  awk 'BEGIN{RS="";FS="\n"}{p=v=c="";for(i=1;i<=NF;i++){t=substr($i,1,2);if(t=="P:")p=substr($i,3);else if(t=="V:")v=substr($i,3);else if(t=="C:")c=substr($i,3)}if(p!="")printf "%s\t%s\t%s\n",p,v,c}' /lib/apk/db/installed \
  | while IFS="$(printf '\t')" read -r p v c; do
      h=""; case "$c" in Q1*) h="$(printf '%s' "${c#Q1}" | base64 -d 2>/dev/null | od -An -tx1 2>/dev/null | tr -d ' \n')";; esac
      printf 'apk\t%s\t%s\t%s\n' "$p" "$v" "$h"
    done
  npm ls -g --depth=0 --json 2>/dev/null | jq -r '(.dependencies // {})|to_entries[]|"npm\t\(.key)\t\(.value.version)\t"' 2>/dev/null
  command -v pip3 >/dev/null 2>&1 && pip3 list --format=json 2>/dev/null | jq -r '.[]|"pip\t\(.key//.name|ascii_downcase)\t\(.value//.version)\t"' 2>/dev/null
  command -v gem  >/dev/null 2>&1 && gem list --local --quiet 2>/dev/null | awk '{name=$1;rest=$0;sub(/^[^(]*\(/,"",rest);sub(/\).*$/,"",rest);n=split(rest,vs,/, */);for(i=1;i<=n;i++){v=vs[i];sub(/^default: */,"",v);if(v!="")printf "gem\t%s\t%s\t\n",name,v}}'
  command -v go   >/dev/null 2>&1 && { gb=""; for d in "$(go env GOBIN 2>/dev/null)" "$(go env GOPATH 2>/dev/null)/bin" /home/sluice/go/bin; do [ -n "$d" ] && [ -d "$d" ] || continue; case " $gb " in *" $d "*) ;; *) gb="$gb $d";; esac; done; for d in $gb; do for f in "$d"/*; do [ -f "$f" ] && [ -x "$f" ] || continue; go version -m "$f" 2>/dev/null | awk '$1=="mod"{printf "go\t%s\t%s\t\n",$2,$3; exit}'; done; done; }
  command -v cargo >/dev/null 2>&1 && { for ch in "${CARGO_HOME:-$HOME/.cargo}" /home/sluice/.cargo /root/.cargo; do [ -f "$ch/.crates2.json" ] || continue; jq -r '.installs|keys[]|split(" ")|"cargo\t\(.[0])\t\(.[1])\t"' "$ch/.crates2.json" 2>/dev/null; break; done; }
  true
} | jq -R -s '
  ( [ split("\n")[] | select(length>0) | split("\t")
      | { eco:.[0], name:.[1], version:.[2], hash:.[3] }
      | .purl = ( if   .eco=="apk"   then "pkg:apk/wolfi/"+.name+"@"+.version+"?arch="+env.SBOM_ARCH+"&distro=wolfi"
                  elif .eco=="npm"   then "pkg:npm/"+.name+"@"+.version
                  elif .eco=="pip"   then "pkg:pypi/"+.name+"@"+.version
                  elif .eco=="go"    then "pkg:golang/"+.name+"@"+.version
                  elif .eco=="cargo" then "pkg:cargo/"+.name+"@"+.version
                  else                    "pkg:gem/"+.name+"@"+.version end ) ]
    | unique_by(.purl) ) as $pkgs
  | if env.SBOM_FORMAT=="spdx"
    then { spdxVersion:"SPDX-2.3", dataLicense:"CC0-1.0", SPDXID:"SPDXRef-DOCUMENT",
           name:env.SBOM_IMAGE, documentNamespace:("https://sluice.invalid/"+env.SBOM_IMAGE),
           creationInfo:{ created:"1970-01-01T00:00:00Z", creators:[ "Tool: sluice-"+env.SBOM_TOOLVER ] },
           packages:[ $pkgs[] | { SPDXID:("SPDXRef-Package-"+(.purl|gsub("[^A-Za-z0-9.-]";"-"))),
                                  name:.name, versionInfo:.version, downloadLocation:"NOASSERTION",
                                  externalRefs:[ { referenceCategory:"PACKAGE-MANAGER", referenceType:"purl", referenceLocator:.purl } ] }
                              + ( if (.hash // "") != "" then { checksums:[ { algorithm:"SHA1", checksumValue:.hash } ] } else {} end ) ],
           relationships:[ $pkgs[] | { spdxElementId:"SPDXRef-DOCUMENT", relationshipType:"DESCRIBES",
                                       relatedSpdxElement:("SPDXRef-Package-"+(.purl|gsub("[^A-Za-z0-9.-]";"-"))) } ] }
    else { bomFormat:"CycloneDX", specVersion:"1.6", version:1,
           metadata:{
             tools:{ components:[ { type:"application", name:"sluice", version:env.SBOM_TOOLVER } ] },
             component:{ type:"container", name:env.SBOM_IMAGE,
                         properties:[ { name:"sluice:base", value:env.SBOM_BASE } ] } },
           components: [ $pkgs[] | { type:"library", "bom-ref":.purl, name:.name, version:.version, purl:.purl }
                                   + ( if (.hash // "") != "" then { hashes:[ { alg:"SHA-1", content:.hash } ] } else {} end ) ] }
    end'
SBOM
}

# `sluice lock --scan [--json] [--fail-on <sev>]`: vuln-scan the box's SBOM with a HOST scanner (grype,
# else trivy - never baked, same as cosign-verify). Report-only by default; --fail-on <severity>
# (negligible|low|medium|high|critical) makes it a CI gate (non-zero on a finding at/above it).
cmd_scan() {
  local json=0 failon=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --json)      json=1 ;;
      --fail-on)   failon="${2:-}"; [ -n "$failon" ] || die "usage: sluice lock --scan [--json] [--fail-on <severity>]"; shift ;;
      --fail-on=*) failon="${1#--fail-on=}" ;;
      *)           die "usage: sluice lock --scan [--json] [--fail-on <negligible|low|medium|high|critical>]" ;;
    esac
    shift
  done
  if [ -n "$failon" ]; then
    case "$failon" in negligible|low|medium|high|critical) ;; *) die "invalid --fail-on '$failon' (negligible|low|medium|high|critical)" ;; esac
  fi

  # Prefer grype (CycloneDX-native); trivy had a 2026 supply-chain compromise, so only as a fallback.
  local scanner=""
  if   command -v grype >/dev/null 2>&1; then scanner=grype
  elif command -v trivy >/dev/null 2>&1; then scanner=trivy; fi
  if [ -z "$scanner" ]; then
    if [ -n "$failon" ]; then die "no vulnerability scanner found but --fail-on was given - install grype to gate on CVEs (https://github.com/anchore/grype)"; fi
    echo "[sluice] ${E_YEL}note${E_RST}: no scanner found - install grype to enable 'lock --scan' (https://github.com/anchore/grype)" >&2
    return 0
  fi

  maybe_build
  local tmp rc; tmp="$(mktemp)"
  cmd_sbom > "$tmp"   # reuse the CycloneDX SBOM; the inner maybe_build is a no-op now, so $tmp is clean
  if [ "$scanner" = grype ]; then
    local ga=(sbom:"$tmp")
    if [ "$json" = 1 ]; then ga+=(-o json); else ga+=(-o table); fi
    if [ -n "$failon" ]; then ga+=(--fail-on "$failon"); fi
    grype "${ga[@]}" && rc=0 || rc=$?
  else
    local sev=""
    case "$failon" in
      critical)   sev=CRITICAL ;;
      high)       sev=HIGH,CRITICAL ;;
      medium)     sev=MEDIUM,HIGH,CRITICAL ;;
      low)        sev=LOW,MEDIUM,HIGH,CRITICAL ;;
      negligible) sev=UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL ;;
    esac
    local ta=(sbom)
    if [ "$json" = 1 ]; then ta+=(--format json); else ta+=(--format table); fi
    if [ -n "$failon" ]; then ta+=(--severity "$sev" --exit-code 1); fi
    trivy "${ta[@]}" "$tmp" && rc=0 || rc=$?
  fi
  rm -f "$tmp"
  return "$rc"
}

# `sluice doctor`: one-shot health + why-egress-is-blocked report
